name: Pegasus
main: io.github.hartorn.Pegasus.Pegasus
version: 0.1 DEV
author: Hartorn
commands: 
    pegasus:
        description: Create a pegasus
        permission: pegasus.create
        permission-message: You're not allowed to create pegasus.
permissions:
    pegasus.*:
        description: Gives access to all pegasus commands
        children:
            pegasus.create: true
    pegasus.create:
        description: Allows you to create pegasus.
        default: op