name: Pegasus
main: io.github.hartorn.Pegasus.Pegasus
version: 0.1 DEV
author: Hartorn
commands: 
    pegasus-create:
        description: Create a pegasus
        permission: pegasus.create
        permission-message: You're not allowed to create pegasus.
    pegasus-customise:
        description: Customise a pegasus
        permission: pegasus.customise
        permission-message: You're not allowed to customise pegasus.
    pegasus-respawn:
        description: Respawn your pegasus, if he is dead or lost.
        permission: pegasus.respawn
        permission-message: You're not allowed to respawn pegasus.
    pegasus-clear:
        description: Kill all not registered Pegasus.
        permission: pegasus.clear
        permission-message: You're not allowed to kill all not registered Pegasus.
    pegasus-forceclear:
        description: Kill all Horses.
        permission: pegasus.forceclear
        permission-message: You're not allowed to kill all horses.
permissions:
    pegasus.player:
        description: Gives access to all pegasus commands for players.
        default: true
        children:
            pegasus.create: true   
            pegasus.customise: true
            pegasus.respawn: true
    pegasus.administration:
        description: Gives access to all pegasus commands for administrators.
        default: op
        children:
            pegasus.forceclear: true
            pegasus.clear: true
    pegasus.create:
        description: Allows you to create pegasus.
        default: true
    pegasus.customise:
        description: Allows you to customise your own pegasus.
        default: true
    pegasus.respawn:
        description: Allows you to respawn your own pegasus.
        default: true
    pegasus.clear:
        description: Allows you to kill all not registered Pegasus.
        default: op
    pegasus.forceclear:
        description: Allows you to kill all horses.
        default: op